language: go
go:
- 1.11.x
addons:
  apt:
    packages:
    - rpm
env:
  global:
  - PATH=/snap/bin:$PATH
  - GO111MODULE=on
  - secure: O9szQGL2eYATFm3r/PwcGJz7iSaQJHFVfqpei8ENDkciIpJaL8blqpGk7etIDdbmZB9cTeXTn0N9lwoPyd04i7dvLfa3VrX3JIYpN1fxm4sJU325zk4B4yAMbSndozU7wbWGVaP6xemThiT+oL0LsNiyzlrEnYXkBSrcBiiwIdhwTikfXa/BztuiW/ow8GwzA9eeb/6hzDAjPAf45MzU3C6ltlrPCUpnlTzDGv0VKfJDxxwLurO389Uxen197nQAUE+A6XQ6uFBWC/f6EJ7GmESqZGNwvmEM7Qmixb7/j1MZBcOBjSA0lPjunys+jYUjVVdryQ9bIZfgtH0CUD96TBFsrpCKVNhBmg2UALk8TV01Y1OvNk/cC8gYTFH82QsSE1BDgALygWc/TpKYXjjUKgwXJSBjE6in2pHHrp3+p8KLYiW6a0Oy/SFAJKItGQ/XSgP8w5tkANShs8shdbHnHmq4VAyW4CIxBd9xnY/lnDrqlqSnag8RnO6iA1VQgM/Ax8lcUjavKldiVMcDEeA+q/yOdFhVPrLL0XMb/VxrTQuvOg8dPRz8PFA1tpLmPGsHpDVROZPq5MtYEw+D71NiY3+Si8JBvMkF7TfRBoYAYLCwI4PkgMZ5vFs+RGTREW3+JS5zV29qrRc9jCo54d2XCObA5ElOfJGUgf9uVQNX7FY=
deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    branch: "master"
    condition: "$TRAVIS_OS_NAME = linux"
    tags: true
before_deploy:
- openssl aes-256-cbc -K $encrypted_ec58356001bc_key -iv $encrypted_ec58356001bc_iv
  -in snap.login.enc -out snap.login -d
